import Foundation
@testable import MarkdownPDF
import Testing

/// Validates the `CFF ` parser against fixtures generated by fontTools (the oracle):
/// the recorded glyph count, CID-keyed flag, and glyph-id to CID charset must match.
@Suite("CFF font parser")
struct CFFFontTests {
    private func cffBytes(_ name: String) throws -> [UInt8] {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/\(name)")
        return try [UInt8](Data(contentsOf: url))
    }

    @Test("Parses a CID-keyed CFF: glyph count, CID flag, and charset match the oracle")
    func parsesCIDKeyedCFF() throws {
        // cid-cff-sample.cff is the `CFF ` table of a 4-glyph subset of Hiragino Sans
        // GB (CID-keyed, Adobe-GB1). fontTools reports: isCID true, 4 glyphs, charset
        // (glyph id -> CID) [0, 357, 4559, 8001].
        let font = try CFFFont(bytes: cffBytes("cid-cff-sample.cff"))
        #expect(font.isCIDKeyed)
        #expect(font.glyphCount == 4)
        #expect(font.charstringType == 2)
        #expect(font.charset == [0, 357, 4559, 8001])
    }

    @Test("Rewrites the CID subset's internal PostScript name")
    func rewritesCIDSubsetPostScriptName() throws {
        let program = try CFFFontProgram(bytes: cffBytes("cid-cff-sample.cff"))
        let subsetName = "ABCDEF+CIDSample"

        let bytes = try CFFSubsetter.subset(
            program: program,
            usedGlyphIDs: Set(0 ..< program.glyphCount),
            postScriptName: subsetName,
        )
        let subset = try CFFFontProgram(bytes: bytes)

        #expect(String(decoding: subset.fontName, as: UTF8.self) == subsetName)
    }

    @Test("Rejects malformed CFF input with a typed error, never trapping")
    func rejectsMalformedCFF() throws {
        // Empty, truncated header, and a wrong major version each throw a typed error.
        #expect(throws: (any Error).self) { _ = try CFFFont(bytes: []) }
        #expect(throws: (any Error).self) { _ = try CFFFont(bytes: [1, 0, 4]) } // truncated header
        #expect(throws: CFFFont.ParseError.self) {
            _ = try CFFFont(bytes: [2, 0, 4, 2, 0, 0, 0, 0]) // major version 2 (CFF2)
        }
    }

    @Test("Bounded fuzz: truncations and corruptions throw, never crash", arguments: 0 ..< 24)
    func boundedFuzzNeverCrashes(_ seed: Int) throws {
        var bytes = try cffBytes("cid-cff-sample.cff")
        // Deterministic mutations keyed on the seed: truncate to a prefix, or flip a
        // structural byte. Every outcome must be a thrown error or a valid parse,
        // never a trap or out-of-bounds read.
        if seed < 12 {
            bytes = Array(bytes.prefix(seed * 3))
        } else {
            let index = (seed * 37) % bytes.count
            bytes[index] = UInt8((Int(bytes[index]) + 129) % 256)
        }
        _ = try? CFFFont(bytes: bytes)
    }
}
