import Foundation

/// Filled rectangles and text origins read straight from uncompressed page content
/// streams, in page order. It is the geometry witness for layout invariants: the
/// numbers come from the generated bytes, not from the renderer's own state.
struct ContentStreamGeometry {
    struct Rect: Equatable {
        var x: Double
        var y: Double
        var width: Double
        var height: Double

        var top: Double {
            y + height
        }

        var bottom: Double {
            y
        }
    }

    /// One drawn text fragment. `y` is the baseline.
    struct Text: Equatable {
        var x: Double
        var y: Double
        var size: Double
        var string: String

        /// Top of the line box under the renderer's convention (`0.75 * size`).
        var top: Double {
            y + size * 0.75
        }

        /// Bottom of the line box (`0.25 * size` below the baseline).
        var bottom: Double {
            y - size * 0.25
        }
    }

    struct Page: Equatable {
        var rects: [Rect] = []
        var texts: [Text] = []
    }

    var pages: [Page]

    init(pdf: Data) {
        pages = PDFInspector(pdf).streams.compactMap { stream in
            let page = Self.parse(stream.body)
            return page.rects.isEmpty && page.texts.isEmpty ? nil : page
        }
    }

    private static func parse(_ body: String) -> Page {
        var page = Page()
        let number = #"(-?[0-9]+(?:\.[0-9]+)?)"#
        let rectPattern = try? Regex("\(number) \(number) \(number) \(number) re f")
        let textPattern = try? Regex(#"/F[0-9]+ "# + number + " Tf " + number + " " + number + #" Td \((.*)\) Tj"#)

        for line in body.split(separator: "\n") {
            let text = String(line)
            if let rectPattern, let match = try? rectPattern.firstMatch(in: text), match.count == 5 {
                let values = (1 ... 4).compactMap { match[$0].substring.flatMap { Double($0) } }
                if values.count == 4 {
                    page.rects.append(Rect(x: values[0], y: values[1], width: values[2], height: values[3]))
                }
            }
            if let textPattern, let match = try? textPattern.firstMatch(in: text), match.count == 5 {
                let values = (1 ... 3).compactMap { match[$0].substring.flatMap { Double($0) } }
                if values.count == 3, let string = match[4].substring {
                    page.texts.append(Text(x: values[1], y: values[2], size: values[0], string: String(string)))
                }
            }
        }
        return page
    }
}
